{
 "title": "Standard Namespace Monitoring",
 "description": "Standard Kubernetes/OpenShift namespace monitoring dashboard (needs Prometheus recording rules)",
 "tags": [
  "kubernetes",
  "openshift",
  "recording-rules",
  "prometheus",
  "namespace"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   { "name": "authors", "label": "Authors", "query": "ONZACK AG and LGT" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\", phase!=\"Succeeded\", namespace=\"$namespace\"})\n+\nsum(changes(kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"}[5m]))\n+\n(sum(kube_job_status_failed{namespace=\"$namespace\"}) OR on() vector(0))\n+\n(sum(kube_replicaset_spec_replicas{namespace=\"$namespace\"}) OR on() vector(0)) - (sum(kube_replicaset_status_ready_replicas{namespace=\"$namespace\"}) OR on() vector(0))\n+\n(sum(kube_statefulset_replicas{namespace=\"$namespace\"}) OR on() vector(0)) - (sum(kube_statefulset_status_replicas_ready{namespace=\"$namespace\"}) OR on() vector(0))\n+\n(sum(kube_daemonset_status_number_misscheduled{namespace=\"$namespace\"})OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "description": "Deployments = Replica missmatch  \nStatefulsets = Replica missmatch  \nDaemonsets = Replica missmatch  ",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{phase!=\"Running\", phase!=\"Succeeded\", namespace=\"$namespace\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(kube_replicaset_spec_replicas{namespace=\"$namespace\"}) - sum(kube_replicaset_status_ready_replicas{namespace=\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=\"$namespace\"})",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(changes(kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"}[5m]))",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum(kube_statefulset_replicas{namespace=\"$namespace\"}) - sum(kube_statefulset_status_replicas_ready{namespace=\"$namespace\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_status_number_misscheduled{namespace=\"$namespace\"})",
     "legendFormat": "Daemonsets"
    }
   ]
  },
  {
   "title": "Workload",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "pods"
    },
    {
     "expr": "count(kube_deployment_spec_replicas{namespace=\"$namespace\"})",
     "legendFormat": "deployments"
    },
    {
     "expr": "count(kube_statefulset_replicas{namespace=\"$namespace\"})",
     "legendFormat": "statefulsets"
    },
    {
     "expr": "count(kube_daemonset_metadata_generation{namespace=\"$namespace\"})",
     "legendFormat": "daemonsets"
    },
    {
     "expr": "count(kube_cronjob_info{namespace=\"$namespace\"})",
     "legendFormat": "cronjobs"
    }
   ]
  },
  {
   "title": "Cores Used (from limits)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_limits:cpu:running{namespace=\"$namespace\"})\n*\nsum(container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Cores Used Top Pod (from limits)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,\n  100\n  /\n  sum by (pod) (kube_pod_container_resource_limits:cpu:running{namespace=\"$namespace\"})\n  *\n  sum by (pod) (container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})\n)"
    }
   ]
  },
  {
   "title": "CPU Cores Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum by (pod) (container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used (from limits)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_limits:memory:running{namespace=\"$namespace\"})\n*\nsum(container_memory_working_set_bytes:sum{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory  Used Top Pod (from limits)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,\n  100\n  /\n  sum by (pod) (kube_pod_container_resource_limits:memory:running{namespace=\"$namespace\"})\n  *\n  sum by (pod) (container_memory_working_set_bytes:sum{namespace=\"$namespace\"})\n)"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes:sum{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage Used (from capacity)",
   "type": "gauge",
   "description": "Persistent Storage",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\nsum(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})\n*\nsum(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Storage Used Top PVC  (from capacity)",
   "type": "gauge",
   "description": "Persistent Storage",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,\n  100\n  /\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})\n  *\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$namespace\"})\n)"
    }
   ]
  },
  {
   "title": "Persistent Storage Used by PVC",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$namespace\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Storage Throughput Read",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_reads_bytes_total:sum_rate5m{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Storage Throughput Write",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_writes_bytes_total:sum_rate5m{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Storage Troughput (read & write) by Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_fs_reads_bytes_total:sum_rate5m{namespace=\"$namespace\"})",
     "legendFormat": "(read) {{pod}}"
    },
    {
     "expr": "sum by (pod) (container_fs_writes_bytes_total:sum_rate5m{namespace=\"$namespace\"}) * -1",
     "legendFormat": "(write) {{pod}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth Receive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total:sum_rate5m{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Network Bandwidth Transmit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total:sum_rate5m{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Network Bandwith (receive & transmit) by Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_network_receive_bytes_total:sum_rate5m{namespace=\"$namespace\"})",
     "legendFormat": "(receive) {{pod}}"
    },
    {
     "expr": "sum by (pod) (container_network_transmit_bytes_total:sum_rate5m{namespace=\"$namespace\"}) * -1",
     "legendFormat": "(transmit) {{pod}}"
    }
   ]
  },
  {
   "title": "Availability / Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Restarts",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by (pod) (changes(kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods in Status Phase = Failed",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum by (pod) (kube_pod_status_phase{phase!=\"Running\", phase=\"Failed\", namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods in Status Phase = Pending",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum by (pod) (kube_pod_status_phase{phase!=\"Running\", phase=\"Pending\", namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods in Status Phase = Unknown",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "sum by (pod) (kube_pod_status_phase{phase!=\"Running\", phase=\"Unknown\", namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Failed Jobs",
     "type": "timeseries",
     "description": "No data means there are no Jobs/CronJobs in this namespace",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum by (job_name) (kube_job_status_failed{namespace=\"$namespace\"})",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Deployments/Replicasets with Replica missmatch",
     "type": "timeseries",
     "description": "No data means there are no Deployments in this namespace",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum by (replicaset) (kube_replicaset_spec_replicas{namespace=\"$namespace\"})\n-\nsum by (replicaset) (kube_replicaset_status_ready_replicas{namespace=\"$namespace\"})\nand\nsum by (replicaset) (kube_replicaset_spec_replicas{namespace=\"$namespace\"}) > 0",
       "legendFormat": "{{replicaset}}"
      }
     ]
    },
    {
     "title": "Statefulsets with Replica missmatch",
     "type": "timeseries",
     "description": "No data means there are no Statefulsets in this namespace",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "sum by (statefulset) (kube_statefulset_replicas{namespace=\"$namespace\"}) - sum by (statefulset) (kube_statefulset_status_replicas_ready{namespace=\"$namespace\"})",
       "legendFormat": "{{statefulset}}"
      }
     ]
    },
    {
     "title": "Daemonsets misscheduled",
     "type": "timeseries",
     "description": "No data means there are no Daemonsets in this namespace",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum by (daemonset) (kube_daemonset_status_number_misscheduled{namespace=\"$namespace\"})",
       "legendFormat": "{{daemonset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace CPU Cores Quota ($namespace)",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"requests.cpu\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"requests.cpu\"})"
      },
      {
       "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"requests.cpu\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"requests.cpu\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.cpu\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"limits.cpu\"})"
      },
      {
       "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.cpu\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"limits.cpu\"})"
      }
     ]
    },
    {
     "title": "Namespace Memory Quota ($namespace)",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"requests.memory\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"requests.memory\"})"
      },
      {
       "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"requests.memory\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"requests.memory\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.memory\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"limits.memory\"})"
      },
      {
       "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.memory\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"limits.memory\"})"
      }
     ]
    },
    {
     "title": "Cores Requested",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Cores Limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Cores  Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Cores Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace=\"$namespace\"})\n-\nsum(container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Cores Wasted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})\n-\nsum(container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"}) > 0"
      }
     ]
    },
    {
     "title": "Memory Requested",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace=\"$namespace\"})\n-\nsum(container_memory_working_set_bytes:sum{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Wasted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"})\n-\nsum(container_memory_working_set_bytes:sum{namespace=\"$namespace\"}) > 0"
      }
     ]
    },
    {
     "title": "Cores Used (from requests)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})\n*\nsum(container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Cores Used (from requests)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})\r\n/\r\nsum(kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Cores Used, Requestes, Limits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})",
       "legendFormat": "requestes"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace=\"$namespace\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Limits/Requests Ratio",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})\n*\nsum(kube_pod_container_resource_limits:cpu:running{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Used (from requests)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"})\n*\nsum(container_memory_working_set_bytes:sum{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Used (from requests)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=\"$namespace\"})\n/\nsum(kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"})",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Memory Used, Requestes, Limits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=\"$namespace\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"})",
       "legendFormat": "requestes"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace=\"$namespace\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Limits/Requests Ratio",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"})\n*\nsum(kube_pod_container_resource_limits:memory:running{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "CPU Cores by Container",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod)(container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod)(container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})\n/\nsum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (avg_over_time(container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"}[1d]) * on(pod,namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))"
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_limits:cpu:running{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (container_cpu_cfs_throttling:percent{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})\n/\nsum by (container, pod) (kube_pod_container_resource_limits:cpu:running{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_limits:cpu:running{namespace=\"$namespace\"})\n/\nsum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})\r\n-\r\nsum by (container, pod) (container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"}) * 0.75 > sum by (container, pod) (container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"}) > 0.1"
      },
      {
       "expr": "sum by (container, pod) (container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})\r\n-\r\nsum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"}) * 1.75 < sum by (container, pod) (container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=\"$namespace\"}) > 0.1"
      }
     ]
    },
    {
     "title": "Memory by Container",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=\"$namespace\"})\n/\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container,pod) (avg_over_time(container_memory_working_set_bytes:sum{namespace=\"$namespace\"}[1d]) * on(pod,namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))"
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_limits:memory:running{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=\"$namespace\"})\n/\nsum by (container, pod) (kube_pod_container_resource_limits:memory:running{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_limits:memory:running{namespace=\"$namespace\"})\n/\nsum by (container, pod) (kube_pod_container_resource_requests{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"})\r\n-\r\nsum by (container, pod) (container_memory_working_set_bytes:sum{namespace=\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"}) * 0.75 > sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"}) > 0.1"
      },
      {
       "expr": "sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=\"$namespace\"})\r\n-\r\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"}) * 1.75 < sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=\"$namespace\"}) > 0.1"
      }
     ]
    },
    {
     "title": "CPU Cores Recommnded by VPA",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum by (container, target_kind, target_name) (kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=\"$namespace\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Memory Recommnded by VPA",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container, target_kind, target_name) (kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=\"$namespace\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Persistent Storage",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$namespace\"})\n/\nsum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (avg_over_time(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}[1d]))"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Persistent Storage Used (from capacity)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$namespace\"})\n/\nsum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores Usage by Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Cores Usage by Container (from limits)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"}\n/\nkube_pod_container_resource_limits:cpu:running{namespace=\"$namespace\"}",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "CPU CFS Throtteling by Containers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "container_cpu_cfs_throttling:percent{namespace=\"$namespace\"}",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage by Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes:sum{namespace=\"$namespace\"}",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage by Container (from limits)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes:sum{namespace=\"$namespace\"}\n/\nkube_pod_container_resource_limits:memory:running{namespace=\"$namespace\"}",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Storage Troughput by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_fs_reads_bytes_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Write Storage Troughput by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_fs_writes_bytes_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Read Storage IOPS by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "container_fs_reads_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Write Storage IOPS by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "container_fs_writes_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{container}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Persistent Storage Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Persistent Storage Used (from capacity)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}\n/\nkubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Network Bandwith by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_network_receive_bytes_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Network Bandwith by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_network_transmit_bytes_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Receive Network Packets by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "container_network_receive_packets_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Network Packets by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "container_network_transmit_packets_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Receive Network Packets Dropped by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "container_network_receive_packets_dropped_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Network Packets Dropped by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "container_network_transmit_packets_dropped_total:sum_rate5m{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}