{
 "title": "GitLab CI Environments & Deployments",
 "description": "This dashboard leverages the Prometheus exporter I wrote to fetch information about GitLab CI pipelines statuses. More information here: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter",
 "tags": [ "GitLab" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "GITLAB_HOST", "query": "${VAR_GITLAB_HOST}" },
   {
    "name": "OWNER",
    "label": "owner",
    "query": {
     "query": "label_values(gitlab_ci_environment_information, project)"
    }
   },
   {
    "name": "PROJECT",
    "label": "project",
    "query": {
     "query": "label_values(gitlab_ci_environment_information{project=~\"$OWNER.*\"}, project)"
    }
   },
   {
    "name": "ENVIRONMENT",
    "label": "environment",
    "query": {
     "query": "label_values(gitlab_ci_environment_information{project=~\"$PROJECT\"}, environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commits behind",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gitlab_ci_environment_behind_commits_count{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"}",
       "legendFormat": "{{ project }} - {{ environment }}"
      }
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "AVAILABLE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_environment_information{available=\"true\", project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "NOT UP TO DATE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_environment_behind_commits_count{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT.*\"} > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "FAILED DEPLOYMENTS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_environment_status{status=\"failed\", project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"} > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "UNAVAILABLE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_environment_information{available=\"false\", project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_ci_environment_deployment_count{project=~\"$PROJECT\",environment=~\"$ENVIRONMENT\"}[5m])) by (project, environment) / \r\nsum(increase(gitlab_ci_environment_deployment_count{project=~\"$PROJECT\",environment=~\"$ENVIRONMENT\"}[5m])) by (project, environment) > 0",
     "legendFormat": "{{ environment }} - {{ project }}"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS # (in the last hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_ci_environment_deployment_count{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"}[1h]))"
    }
   ]
  },
  {
   "title": "Average environment deployment lag commits count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gitlab_ci_environment_behind_commits_count{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"})"
    }
   ]
  },
  {
   "title": "Average environment deployment lag duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gitlab_ci_environment_behind_duration_seconds{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"})",
     "legendFormat": "avg_deployment_lag"
    }
   ]
  },
  {
   "title": "ENVIRONMENTS",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(max(gitlab_ci_environment_deployment_status{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\", status=~\"success\"}) by (project, environment) * 1) > 0 or\n(max(gitlab_ci_environment_deployment_status{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\", status=~\"running\"}) by (project, environment) * 2) > 0 or\n(max(gitlab_ci_environment_deployment_status{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\", status=~\"failed\"}) by (project, environment) * 3) > 0 or\n(max(gitlab_ci_environment_deployment_status{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\", status=~\"canceled\"}) by (project, environment) * 4) > 0 or\n(max(gitlab_ci_environment_deployment_status{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\", status=~\"skipped\"}) by (project, environment) * 5) > 0 or\n(max(gitlab_ci_environment_deployment_status{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\", status=~\"created|waiting_for_resource|preparing|pending|manual|scheduled\"}) by (project, environment) * 6) > 0"
    },
    {
     "expr": "-max(time() - gitlab_ci_environment_deployment_timestamp{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"}) by (project, environment)"
    },
    {
     "expr": "max(gitlab_ci_environment_deployment_duration_seconds{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"}) by (project, environment)"
    },
    {
     "expr": "max(gitlab_ci_environment_information{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"}) by (environment_id, project, environment, author_email, current_commit_short_id, ref, latest_commit_short_id)"
    },
    {
     "expr": "max(gitlab_ci_environment_behind_commits_count{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"}) by (project, environment)"
    },
    {
     "expr": "max(gitlab_ci_environment_behind_duration_seconds{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"}) by (project, environment)"
    },
    {
     "expr": "max(gitlab_ci_environment_deployment_job_id{project=~\"$PROJECT\", environment=~\"$ENVIRONMENT\"}) by (project, environment)"
    }
   ]
  }
 ]
}