{
 "title": "Systemd Service Monitoring",
 "description": "Show stats from node_exporter systemd collector.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{state=\"failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed (all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node, name, state) (node_systemd_unit_state{state=\"failed\"} * on(instance) group_left(node) label_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\")) > 0",
     "legendFormat": "{{name}}, node {{node}"
    }
   ]
  },
  {
   "title": "Inactive (all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node, name, state) (node_systemd_unit_state{state=\"inactive\"} * on(instance) group_left(node) label_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\")) > 0",
     "legendFormat": "{{name}}, node {{node}}"
    }
   ]
  },
  {
   "title": "Node State",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(node, state) (node_systemd_unit_state * on(instance, pod) group_left(node) label_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active (all nodes)",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(node, name) (node_systemd_unit_state{state=\"active\"} * on(instance, pod) group_left(node) label_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\")) > 0"
    }
   ]
  },
  {
   "title": "Activating (all nodes)",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum by(node, name) (node_systemd_unit_state{state=\"activating\"} * on(instance, pod) group_left(node) label_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\")) > 0"
    }
   ]
  },
  {
   "title": "Deactivating (all nodes)",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum by(node, name) (node_systemd_unit_state{state=\"deactivating\"} * on(instance, pod) group_left(node) label_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\")) > 0"
    }
   ]
  }
 ]
}