{
 "title": "ONZACK - Namespace Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\", phase!=\"Succeeded\", namespace=\"$namespace\"})\n+\nsum(changes(kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"}[5m]))\n+\n(sum(kube_job_status_failed{namespace=\"$namespace\"}) OR on() vector(0))\n+\n(sum(kube_replicaset_spec_replicas{namespace=\"$namespace\"}) OR on() vector(0)) - (sum(kube_replicaset_status_ready_replicas{namespace=\"$namespace\"}) OR on() vector(0))\n+\n(sum(kube_statefulset_replicas{namespace=\"$namespace\"}) OR on() vector(0)) - (sum(kube_statefulset_status_replicas_ready{namespace=\"$namespace\"}) OR on() vector(0))\n+\n(sum(kube_daemonset_status_number_misscheduled{namespace=\"$namespace\"})OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\", phase!=\"Succeeded\", namespace=\"$namespace\"}) by (phase)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(kube_replicaset_spec_replicas{namespace=\"$namespace\"}) - sum(kube_replicaset_status_ready_replicas{namespace=\"$namespace\"})",
     "legendFormat": "Deploymetns"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=\"$namespace\"})",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(changes(kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"}[5m]))",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum(kube_statefulset_replicas{namespace=\"$namespace\"}) - sum(kube_statefulset_status_replicas_ready{namespace=\"$namespace\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_status_number_misscheduled{namespace=\"$namespace\"})",
     "legendFormat": "Daemonsets"
    }
   ]
  },
  {
   "title": "Workload",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "pods"
    },
    {
     "expr": "count(kube_deployment_spec_replicas{namespace=\"$namespace\"})",
     "legendFormat": "deployments"
    },
    {
     "expr": "count(kube_statefulset_replicas{namespace=\"$namespace\"})",
     "legendFormat": "statefulsets"
    },
    {
     "expr": "count(kube_daemonset_metadata_generation{namespace=\"$namespace\"})",
     "legendFormat": "daemonsets"
    },
    {
     "expr": "count(kube_cronjob_info{namespace=\"$namespace\"})",
     "legendFormat": "cronjobs"
    }
   ]
  },
  {
   "title": "Cores Used (from limits)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n*\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=\"$namespace\"}[5m]))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cores Used Top Pod (from limits)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,\n  100\n  /\n  sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod)\n  *\n  sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=\"$namespace\"}[5m])) by (pod)\n)"
    }
   ]
  },
  {
   "title": "CPU Cores Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used (from limits)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n*\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory  Used Top Pod (from limits)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,\n  100\n  /\n  sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod)\n  *\n  sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=\"$namespace\"}) by (pod)\n)"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage Throughput Read",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{container!=\"\", namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Storage Throughput Write",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container!=\"\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Storage Troughput (read & write) by Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{container!=\"\", namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "read-{{pod}}"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container!=\"\",namespace=\"$namespace\"}[5m])) by (pod) * -1",
     "legendFormat": "write-{{pod}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth Reveive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Bandwidth Transmit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Bandwith (receive & transmit) by Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "receive/{{pod}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod) * -1",
     "legendFormat": "transmit/{{pod}}"
    }
   ]
  },
  {
   "title": "Capacity Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namesapce CPU Cores Quota ($namespace)",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"requests.cpu\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"requests.cpu\"}) by (namespace)"
      },
      {
       "expr": "100 / sum(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"requests.cpu\"}) by (namespace) * sum(kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"requests.cpu\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.cpu\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"limits.cpu\"}) by (namespace)"
      },
      {
       "expr": "100 / sum(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.cpu\"}) by (namespace) * sum(kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"limits.cpu\"}) by (namespace)"
      }
     ]
    },
    {
     "title": "Namesapce Memory Quota ($namespace)",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"requests.memory\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"requests.memory\"}) by (namespace)"
      },
      {
       "expr": "100 / sum(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"requests.memory\"}) by (namespace) * sum(kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"requests.memory\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.memory\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"limits.memory\"}) by (namespace)"
      },
      {
       "expr": "100 / sum(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.memory\"}) by (namespace) * sum(kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"limits.memory\"}) by (namespace)"
      }
     ]
    },
    {
     "title": "Cores Requested",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))"
      }
     ]
    },
    {
     "title": "Cores Limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))"
      }
     ]
    },
    {
     "title": "Cores  Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Cores Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n-\nsum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Cores Wasted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n-\nsum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) > 0"
      }
     ]
    },
    {
     "title": "Memory Requested",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))"
      }
     ]
    },
    {
     "title": "Memory Limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n-\nsum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Wasted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n-\nsum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}) > 0"
      }
     ]
    },
    {
     "title": "Cores Used (from requests)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n*\nsum(rate(container_cpu_usage_seconds_total{container!=\"\", contianer!=\"POD\", namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cores Used (from requests)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n*\nsum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]))",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Cores Used, Requestes, Limits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]))",
       "legendFormat": "used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))",
       "legendFormat": "requestes"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Limits/Requests Ratio",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n*\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Used (from requests)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n*\nsum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Used (from requests)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n*\nsum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"})",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Memory Used, Requestes, Limits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))",
       "legendFormat": "requestes"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Limits/Requests Ratio",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n*\nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Cores by Container",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (container, pod)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (container, pod)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (container, pod)\n*\nsum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (container, pod)"
      },
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (container, pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (container, pod)"
      },
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod, container)\n/\nsum(increase(container_cpu_cfs_periods_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod, container)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (container, pod)\n*\nsum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (container, pod)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (container, pod)\n*\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (container, pod)"
      }
     ]
    },
    {
     "title": "Memory by Container",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod, container)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod, container)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod, container)\n*\nsum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}) by (pod, container)"
      },
      {
       "expr": "sum(avg_over_time(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[1d]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod, container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod, container)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod, container)\n*\nsum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}) by (pod, container)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod)\n*\nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (pod)"
      }
     ]
    },
    {
     "title": "CPU Cores Recommnded by VPA",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum by (container, target_kind, target_name) (kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=\"$namespace\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Memory Recommnded by VPA",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container, target_kind, target_name) (kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=\"$namespace\", resource=\"memory\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores Usage by Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (pod, container)",
       "legendFormat": "{{container}}/{{pod}}"
      }
     ]
    },
    {
     "title": "CPU CFS Throtteling by Containers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (pod, container)\n/\nsum(increase(container_cpu_cfs_periods_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (pod, container)",
       "legendFormat": "{{container}}/{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage by Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}) by (pod, container)",
       "legendFormat": "{{container}}/{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Network Usage by Pod",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total{namespace=\"$namespace\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"$namespace\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=\"$namespace\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\"}[5m])) by (pod)"
      }
     ]
    },
    {
     "title": "Reveive Network Bandwith by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reveive Network Packets by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Network Bandwith by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Network Packets by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reveive Network Packets Dropped by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Network Packets Dropped by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Storage Usage by Container",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (pod, container)"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (pod, container)"
      },
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\", namespace=\"$namespace\"}[5m])) by (pod, container)"
      },
      {
       "expr": "sum(rate(container_fs_reads_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by(pod, container)"
      },
      {
       "expr": "sum(rate(container_fs_writes_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by(pod, container)"
      },
      {
       "expr": "sum(rate(container_fs_reads_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]) + rate(container_fs_writes_total{container!=\"\", namespace=\"$namespace\"}[5m])) by (pod, container)"
      }
     ]
    },
    {
     "title": "Read Storage Troughput by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (pod, container)",
       "legendFormat": "{{container}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Read Storage IOPS by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (pod, container)",
       "legendFormat": "{{container}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Write Storage Troughput by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{container!=\"\", container!=\"POD\",namespace=\"$namespace\"}[5m])) by (pod, container)",
       "legendFormat": "{{container}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Write Storage IOPS by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_total{container!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (pod, container)",
       "legendFormat": "{{container}}/{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}