{
 "title": "OPNsense & IDS/IPS",
 "tags": [
  "Security",
  "Firewall",
  "IDS/IPS",
  "OPNsense"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({job=\"syslog-ids\"}, host)"
   },
   { "name": "searchregex", "label": "Search-Regex" }
  ]
 },
 "panels": [
  {
   "title": "Firewall Base Search (do not delete)",
   "type": "logs",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=\"$host\"}\n|~ \"block|pass\" # filter to get only firewall logs\n!= \"icmp\" # filter only not ICMP packages\n| pattern `<_>,<_>,<_>,<RuleID>,<Interface>,<Reason>,<Action>,<Direction>,<IPVersion>,<_>,<_>,<TTL>,<ID>,<Offset>,<IPFlags>,<ProtocolNr>,<Protocol>,<Length>,<SourceIP>,<DestinationIP>,<SourcePort>,<DestinationPort>,<_>,<TCPFlags>,<Seq>,<_>,<_>`"
    },
    {
     "expr": "{job=\"syslog\", host=\"$host\"}\n|~ \"block|pass\" # filter to get only firewall logs\n|= \"icmp\" # filter only ICMP packages\n| pattern `<_>,<_>,<_>,<RuleID>,<Interface>,<Reason>,<Action>,<Direction>,<IPVersion>,<_>,<_>,<TTL>,<ID>,<Offset>,<IPFlags>,<ProtocolNr>,<Protocol>,<Length>,<SourceIP>,<DestinationIP>,<_>`"
    }
   ]
  },
  {
   "title": "IDS Base Search (do not delete)",
   "type": "logs",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"syslog-ids\",host=\"$host\"} != \"Drop\" |~ \"$searchregex\"\n|= \"Priority\" # filter to exclude not IDS/IPS events\n| pattern `[<_>:<ruleId>:<_>] <rule> [Classification: <classification>] [Priority: <priority>] {<protocol>} <sourceIP>:<sourcePort> -> <destinationIP>:<destinationPort>`\n| protocol!~\"IPv6.*\" "
    },
    {
     "expr": "{job=\"syslog-ids\",host=\"$host\"} |= \"Drop\" |~ \"$searchregex\"\n|= \"Priority\" # filter to exclude not IDS/IPS events\n| pattern `[<action>] [<_>:<ruleId>:<_>] <rule> [Classification: <classification>] [Priority: <priority>] {<protocol>} <sourceIP>:<sourcePort> -> <destinationIP>:<destinationPort>`\n| protocol!~\"IPv6.*\" "
    },
    {
     "expr": "{job=\"syslog-ids\",host=\"$host\"} != \"Drop\" |~ \"$searchregex\"\n|= \"Priority\" # filter to exclude not IDS/IPS events\n| pattern `[<action>] [<_>:<ruleId>:<_>] <rule> [Classification: <classification>] [Priority: <priority>] {<protocol>} <_>`\n| protocol=~\"IPv6.*\" # filter only IPv6 logs because pattern() cannot easy handle IPv6 that's why the following regex is used\n| regexp `(?P<sourceIP>(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))):(?P<sourcePort>\\d+) -> (?P<destinationIP>(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))):(?P<destinationPort>\\d+)`\n| label_format sourceIP=`{{ regexReplaceAllLiteral \"\\\\b(?:0+:){2,}\" .sourceIP \":\"}}`\n| label_format sourceIP=`{{ regexReplaceAllLiteral \"(:0+){1}\" .sourceIP \":\"}}`\n| label_format destinationIP=`{{ regexReplaceAllLiteral \"\\\\b(?:0+:){2,}\" .destinationIP \":\"}}`\n| label_format destinationIP=`{{ regexReplaceAllLiteral \"(:0+){1}\" .destinationIP \":\"}}`"
    },
    {
     "expr": "{job=\"syslog-ids\",host=\"$host\"} |= \"Drop\" |~ \"$searchregex\"\n|= \"Priority\" # filter to exclude not IDS/IPS events\n| pattern `[<action>] [<_>:<ruleId>:<_>] <rule> [Classification: <classification>] [Priority: <priority>] {<protocol>} <_>`\n| protocol=~\"IPv6.*\" # filter only IPv6 logs because pattern() cannot easy handle IPv6 that's why the following regex is used\n| regexp `(?P<sourceIP>(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))):(?P<sourcePort>\\d+) -> (?P<destinationIP>(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))):(?P<destinationPort>\\d+)`\n| label_format sourceIP=`{{ regexReplaceAllLiteral \"\\\\b(?:0+:){2,}\" .sourceIP \":\"}}`\n| label_format sourceIP=`{{ regexReplaceAllLiteral \"(:0+){1}\" .sourceIP \":\"}}`\n| label_format destinationIP=`{{ regexReplaceAllLiteral \"\\\\b(?:0+:){2,}\" .destinationIP \":\"}}`\n| label_format destinationIP=`{{ regexReplaceAllLiteral \"(:0+){1}\" .destinationIP \":\"}}`"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Firewall Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog\",host=\"$host\"}[$__range]))"
    }
   ]
  },
  {
   "title": "IDS Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog-ids\", host=\"$host\"} |~ \"$searchregex\" [$__range]))"
    }
   ]
  },
  {
   "title": "Firewall Connections",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 23 }
   ]
  },
  {
   "title": "Firewall Connections",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 23 }
   ]
  },
  {
   "title": "Firewall Connections by DestinationPort",
   "type": "piechart",
   "description": "Top 10 dropped inbound Firewall connections.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 23 }
   ]
  },
  {
   "title": "Potential Attacks",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Potential Attacks from",
   "type": "piechart",
   "description": "Top 5 dropped potential attacks.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Potential Attacks by DestinationPort",
   "type": "piechart",
   "description": "Top 10 dropped potential attacks by port.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Firewall Connections",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "panelId": 23 }
   ]
  },
  {
   "title": "Potential Attacks from",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Firewall Connections by Protocol",
   "type": "piechart",
   "description": "Dropped Inbound Firewall Connections",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 23 }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 23 },
   "targets": [
    { "panelId": 23 }
   ]
  },
  {
   "title": "Potential Attacks by Protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Firewall Logs",
     "type": "table",
     "gridPos": { "h": 20, "w": 12, "x": 0, "y": 39 },
     "targets": [
      { "panelId": 23 }
     ]
    },
    {
     "title": "Blocked by IDS/IPS Rules",
     "type": "logs",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
     "targets": [
      { "panelId": 20 }
     ]
    },
    {
     "title": "Allowed by IDS/IPS Rules",
     "type": "logs",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "targets": [
      { "panelId": 20 }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Other IDS related Logs",
     "type": "logs",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "{job=\"syslog-ids\",host=\"$host\"} \n|~ \"$searchregex\"\n!~ \"\\\\[\\\\d:\\\\d+:\\\\d\\\\]\""
      }
     ]
    }
   ]
  }
 ]
}